service: bus-service

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-2
  memorySize: 512
  # ecr:
  #   # In this section you can define images that will be built locally and uploaded to ECR
  #   images:
  #     appimage:
  #       path: ./

functions:
  busFunc:
    # image:
    #   name: appimage
      # entryPoint:
      #   - '/lambda-entrypoint.sh'
    handler: index.handler
    events:
      # - httpApi: '*'

      - http:
          path: bus
          method: get
          cors: true
      - http:
          path: bus/{id}
          method: get
          cors: true
      - http:
          path: bus
          method: post
          cors: true
      - http:
          path: bus/{id}
          method: put
          cors: true
      - http:
          path: bus/{id}
          method: delete
          cors: true

      - http:
          path: sensordata
          method: get
          cors: true
      - http:
          path: sensordata/{id}
          method: get
          cors: true
      - http:
          path: sensordata
          method: post
          cors: true
      - http:
          path: sensordata/{id}
          method: put
          cors: true
      - http:
          path: sensordata/{id}
          method: delete
          cors: true
        
       

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000