service: bus-service

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-2
  memorySize: 512

functions:
  busFunc:
    handler: index.handler
    events:
      # - httpApi: '*'

      - http:
          path: bus
          method: get
          cors: true
      - http:
          path: bus/{id}
          method: get
          cors: true
      - http:
          path: bus
          method: post
          cors: true
      - http:
          path: bus/{id}
          method: put
          cors: true
      - http:
          path: bus/{id}
          method: delete
          cors: true

      - http:
          path: sensordata/{id}
          method: get
          cors: true
      - http:
          path: sensordata
          method: post
          cors: true
      - http:
          path: sensordata/{id}
          method: put
          cors: true
      - http:
          path: sensordata/{id}
          method: delete
          cors: true
      
      # - http:
      #     path: route
      #     method: get
      # - http:
      #     path: route/{id}
      #     method: get
      # - http:
      #     path: route
      #     method: post
      # - http:
      #     path: route/{id}
      #     method: delete
      
      # - http:
      #     path: stop
      #     method: get
      # - http:
      #     path: stop/{id}
      #     method: get
      # - http:
      #     path: stop
      #     method: post
      # - http:
      #     path: stop/{id}
      #     method: delete

plugins:
  - serverless-offline