# HPA Logic goes here

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: serverless-app-deployment
  namespace: serverless-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: serverless-app-deployment
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
 